#!/usr/bin/env python3
"""
Visualize the 10-lens manifold from hepdata_to_dashi outputs.

Reads per-observable lenses_continuous.csv (generated by the field-first pipeline),
stacks all bins into a single point cloud in R^10, and produces:

- PCA 2D + 3D scatter plots (always)
- Isomap 2D + 3D plots (optional; requires scikit-learn)

Coloring:
- by observable label (default)
- optionally by a specific lens value (--color-lens 0..9)

Usage:
  python 26_hepdata_lens_manifold.py --inp hepdata_to_dashi --out lens_manifold_out
"""

from __future__ import annotations

import argparse
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt


def load_all_points(inp: Path):
    pts = []
    labels = []
    bins = []
    for obs_dir in sorted([p for p in inp.iterdir() if p.is_dir()]):
        csvp = obs_dir / "lenses_continuous.csv"
        if not csvp.exists():
            continue
        data = np.loadtxt(csvp, delimiter=",", skiprows=1)
        # cols: bin, L0..L9
        X = data[:, 1:11]
        pts.append(X)
        labels += [obs_dir.name] * X.shape[0]
        bins += list(data[:, 0].astype(int))
    if not pts:
        raise SystemExit(f"No lenses_continuous.csv found under: {inp}")
    P = np.vstack(pts)
    labels = np.array(labels, dtype=object)
    bins = np.array(bins, dtype=int)
    return P, labels, bins


def pca_fit_transform(X: np.ndarray, d: int):
    Xc = X - X.mean(axis=0, keepdims=True)
    U, S, Vt = np.linalg.svd(Xc, full_matrices=False)
    Z = Xc @ Vt[:d].T
    expl = (S**2) / (len(X) - 1)
    expl_ratio = expl / expl.sum()
    return Z, expl_ratio[:d]


def maybe_isomap(X: np.ndarray, d: int, n_neighbors: int):
    try:
        from sklearn.manifold import Isomap
    except Exception as e:
        return None, None, str(e)
    iso = Isomap(n_neighbors=n_neighbors, n_components=d)
    Z = iso.fit_transform(X)
    return Z, None, None


def scatter2d(Z, labels, outpath: Path, title: str, color_by=None):
    plt.figure(figsize=(9, 6))
    if color_by is None:
        uniq = list(dict.fromkeys(labels.tolist()))
        for u in uniq:
            m = labels == u
            plt.scatter(Z[m, 0], Z[m, 1], s=20, alpha=0.7, label=u)
        plt.legend(loc="best", fontsize=8)
    else:
        plt.scatter(Z[:, 0], Z[:, 1], s=20, alpha=0.8, c=color_by)
        plt.colorbar(label="value")
    plt.title(title)
    plt.xlabel("dim 1")
    plt.ylabel("dim 2")
    plt.grid(True, alpha=0.25)
    plt.tight_layout()
    plt.savefig(outpath, dpi=180)
    plt.close()


def scatter3d(Z, labels, outpath: Path, title: str, color_by=None):
    from mpl_toolkits.mplot3d import Axes3D  # noqa: F401
    fig = plt.figure(figsize=(9, 7))
    ax = fig.add_subplot(111, projection="3d")
    if color_by is None:
        uniq = list(dict.fromkeys(labels.tolist()))
        for u in uniq:
            m = labels == u
            ax.scatter(Z[m, 0], Z[m, 1], Z[m, 2], s=18, alpha=0.7, label=u)
        ax.legend(loc="best", fontsize=8)
    else:
        p = ax.scatter(Z[:, 0], Z[:, 1], Z[:, 2], s=18, alpha=0.85, c=color_by)
        fig.colorbar(p, ax=ax, shrink=0.7, label="value")
    ax.set_title(title)
    ax.set_xlabel("dim 1")
    ax.set_ylabel("dim 2")
    ax.set_zlabel("dim 3")
    plt.tight_layout()
    plt.savefig(outpath, dpi=180)
    plt.close()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--inp", required=True, help="hepdata_to_dashi output directory")
    ap.add_argument("--out", default="lens_manifold_out", help="output directory")
    ap.add_argument("--color-lens", type=int, default=None,
                    help="if set, color points by that lens value (0..9) instead of by observable")
    ap.add_argument("--isomap-neighbors", type=int, default=8, help="neighbors for Isomap (if available)")
    args = ap.parse_args()

    inp = Path(args.inp)
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    X, labels, _ = load_all_points(inp)

    color_by = None
    if args.color_lens is not None:
        if not (0 <= args.color_lens <= 9):
            raise SystemExit("--color-lens must be 0..9")
        color_by = X[:, args.color_lens]

    Z2, er2 = pca_fit_transform(X, 2)
    Z3, er3 = pca_fit_transform(X, 3)

    scatter2d(Z2, labels, out / "pca_2d.png",
              f"PCA 2D (explained: {er2[0]:.3f}, {er2[1]:.3f})", color_by=color_by)
    scatter3d(Z3, labels, out / "pca_3d.png",
              f"PCA 3D (explained: {er3[0]:.3f}, {er3[1]:.3f}, {er3[2]:.3f})", color_by=color_by)

    Z2i, _, err = maybe_isomap(X, 2, args.isomap_neighbors)
    if Z2i is None:
        (out / "isomap_unavailable.txt").write_text(
            "Isomap unavailable (scikit-learn missing or import failed).\n"
            f"Error: {err}\n",
            encoding="utf-8"
        )
    else:
        scatter2d(Z2i, labels, out / "isomap_2d.png",
                  f"Isomap 2D (k={args.isomap_neighbors})", color_by=color_by)
        Z3i, _, _ = maybe_isomap(X, 3, args.isomap_neighbors)
        scatter3d(Z3i, labels, out / "isomap_3d.png",
                  f"Isomap 3D (k={args.isomap_neighbors})", color_by=color_by)

    print(f"Wrote manifold plots to: {out.resolve()}")


if __name__ == "__main__":
    main()
